name: notify of pull_request creation
on:
  pull_request:
    types: [ opened ]
    branches:
      - main

jobs:
  notify:
    defaults:
      run:
        working-directory: ./.github/workflows/notify_on_pull_request_open

    name: notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: get contribution report
        shell: bash
        run: |
          ./build_pull_request_notification.sh $GITHUB_EVENT_PATH
#           GITHUB_TOKEN=${{ secrets.BOT_GITHUB_TOKEN }} ./get_contribution_report.sh > contributions_report_message
#       - name: send contribution report to osscameroon channel
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_OSSCAMEROON_CHANNEL_ID }}
#           token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           format: MarkdownV2
#           message_file: ./.github/workflows/report_contributions/contributions_report_message
#       - name: send contribution report to osscameroon channel
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_OSSCAMEROON_CHANNEL_ID }}
#           token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           format: MarkdownV2
#           message_file: ./.github/workflows/report_contributions/contributions_report_message
