name: telegram github contribution report
on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/report_contributions

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: get yotas issues
        shell: bash
        run: |
          GITHUB_TOKEN=${{ secrets.BOT_GITHUB_TOKEN }} ./get_contribution_report.sh > contributions_report_message

      - name: send contribution report to osscameroon channel
        uses: appleboy/telegram-action@master
        with:
#           to: ${{ secrets.TELEGRAM_OSSCAMEROON_CHANNEL_ID }}
          to: ${{ secrets.TELEGRAM_TEST_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_file: ./.github/workflows/report_contributions/contributions_report_message

#       - name: send contribution report to osscameroon group
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_OSSCAMEROON_GROUP_ID }}
#           token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           message_file: ./.github/workflows/report_contributions/contributions_report_message
