name: telegram github opencollective report
on: [push]
  # schedule:
  #   - cron: "0 13 * * 5"

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/opencollective_contributions

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: get contribution report
        shell: bash
        run: |
          ./get_opencollective_info.sh > contributions_report_message

      - name: send opencollective contribution report to osscameroon group
        uses: appleboy/telegram-action@master
        with:
          to: 267092256
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: MarkdownV2
          message_file: ./.github/workflows/opencollective_contributions/contributions_report_message
