name: telegram issue recommandations
on:
  schedule:
  - cron: '* 1 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_OSSCAMEROON_CHANNEL_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        args: The ${{ github.event_name }} event triggered first step.
